### ISSUE TITLE
Client side web socket for mono

### ISSUE THREAD

**Issue by steforster** [vtortola/WebSocketListener#10]
Hi,
What would you recommend to use as a client side web socket running on mono ?
Do you have plans to add this feature to your library ?
Thanks!

**Comment by vtortola** [comment]
Hi,

I am afraid I use only the server side of WebSockets, as client I always use a browser. I do not work with client applications. I tried once to use the one in Alchemy and failed because my domain name contained more than two subdomains, so ... never tried again. I have used several times the default Microsoft once from a virtual machine, and it is not great either. I have no plans in adding client functionality in the near future, since I am quite busy with other things at the moment.

Cheers.

**Comment by tastywheattasteslikechicken** [comment]
Is it possible to second this request? I have to say I think this is the best listener library for C# (it's the only one that I can find that supports Windows 7 + async), it would be great if you had a chance to add a Client.

**Comment by vtortola** [comment]
Thanks for the kind words :) However I have limited free time and I need to focus in other things :(
