### ISSUE TITLE
Mix of sync and async

### ISSUE THREAD

**Issue by asdfgasdfsafgsdfa** [vtortola/WebSocketListener#105]
Hey, I'm currently debugging some issues with my async code and while reading the source of WebSocketListener I noticed something strange.

https://github.com/vtortola/WebSocketListener/blob/master/vtortola.WebSockets.Rfc6455/WebSocketConnectionRfc6455.cs#L124,#L131

In line 124 you're reading from the network stream.
Let's say there's already some data here. In that case the call completes synchronously and we're still on the original calling thread.
Now in line 131 we're entering "ParseHeader". (Line 217)
The first TryReadHeaderUntil() will instantly succeed as we already read 6 bytes, nothing special here.
Now In line 227 we can't be sure that enough data is present, maybe only the header has arrived so far, yet we're synchronously waiting for the data.

This would block the caller of "AwaitHeaderAsync" (and therefore its caller, and so on...), right?

If you take a look at where AwaitHeaderAsync is called from, you can see "ReadMessageAsync" and there's no Task.Run() or anything that would pass control to a background thread (and I would not advise doing that).

Am I right in assuming this would potentially block a thread with a synchronous network read even though it **looks** like all functions are async?
If it's as I'm assuming this should (Imho) be fixed by:

1. Not doing network reading in a function whos name says it only parses (remove all network reading from ParseHeader)
2. Making whatever got refactored out of ParseHeader async i.e. not doing any synchronous reads (or if doing them maybe rather check the .Available property on the socket, do the read synchronously as we know it won't block, and then if we still don't have enough, enqueue the blocking read in a Task.Run() )

Let me know what you think :)

**Comment by vtortola** [comment]
First of all, sorry for the delay in answering.

Yes. The reason is that the component expects the header to be in the buffer. For example, you get the first 6 bytes, and it indicates that the header is longer than that, it continues reading synchronously because it assumes the data is there already. Headers are small, and usually you would get the header and part of the message if not the whole message. There is chances that the data is not there and it would block the thread as you correctly said, but in my tests this was never the case. By the moment that you get data in the buffer, although the message is not complete, the header usually is, so I saw no reason for making it asynchronous as well, mostly for not having to add async counterparts for those methods.

So yes, you are right, but I could not prove that making that part async as well would improve anything, so I decided not to change it :)

**Comment by asdfgasdfsafgsdfa** [comment]
That is reasonable.
Thank you for explaining.

In our project we often have to deal with potentially very slow/unreliable connections, that's why I was concerned about that.
I will do some actual tests "in the wild" to see if that situation actually happens and how much impact it has.

**Comment by vtortola** [comment]
Fixed in 2.2.3
