### ISSUE TITLE
Question about your code regarding Int32 or int

### ISSUE THREAD

**Issue by StefH** [vtortola/WebSocketListener#20]
This is just matter of personal preference I guess, but whats your exact reason to use *Int32* instead of *int*. Also *Boolean* instead of *bool*?

See also this related stackoverflow discussion:
http://stackoverflow.com/questions/62503/c-int-or-int32-should-i-care

**Comment by vtortola** [comment]
Many years ago I read CLR via C# from Jeffrey Richter, and his arguments regarding using BCL types instead the alias convinced me. Despite the existence of alias like "int" or "bool", all the .NET methods that mention types, will name the BCL type like "ToString", "ToInt32", "ReadBoolean", "ReadInt32", etc... besides, VisualStudio colours types as light blue and keywords like dark blue, so using the BCL types it is easier to identify the types. Also, alias are not consistent since not all value types have an alias, neither all aliased types are value types. There is only one flaw :) you cannot return "System.Void", the compiler requires you to return "void". The alias exists to conform with a specification, but they have not usefulness beyond that.

As you said it is a matter of personal preference, but I like to keep it consistent in my projects.

**Comment by StefH** [comment]
OK. It's your personal preference.

(BTW: I did use/see/create a lot of C# projects, and this is actually the first C# project which uses this convention.)
