### ISSUE TITLE
HttpRequest URI

### ISSUE THREAD

**Issue by ramlongcat** [vtortola/WebSocketListener#22]
When accepting a WebSocket client it seems the HttpRequest URI is not absolute, and hence wrong (almost all Uri type properties throw an exception). It is missing the protocol and hostname/port.

**Comment by vtortola** [comment]
That is because that property contains the info provided by the client as part of the GET, that is relative, always. The HttpRequest is basically representing what info comes in the HTTP request.

You can check `ws.HttpRequest.Headers.Origin` to evaluate the **Origin** header, and the `ws.HttpRequest.Headers.Host` to find out the **Host** header.

**Comment by ramlongcat** [comment]
thanks!
