### ISSUE TITLE
Testability

### ISSUE THREAD

**Issue by ramlongcat** [vtortola/WebSocketListener#23]
Most classes in the library are either sealed, non-abstract or have no virtual methods which makes it hard/painful to fully unit test anything that uses those types.

The ideal would be that they implement public interfaces so they can easily be mocked.

For now the only way I found to fully unit test my code is to wrap your API with classes that just implement the interfaces I use, but that makes the whole thing harder to understand than it would otherwise.

Any plan to improve this in a future update ?

**Comment by vtortola** [comment]
How would you unit test the TcpListener class? :)

This is a component that you should use to fulfil your contracts without exposing it, and without leaking its implementation details to other parts of your application.

This component is already unit tested, and in your tests, you should mock whatever implementation uses it.

**Comment by ramlongcat** [comment]
I don't want to unit test your library which as you said is already unit tested.
My idea was more like having the WebSocketListener implement a IWebSocketListener interface I could mock in my unit tests. Right now the WebSocketListener is sealed and has no virtual methods so it's hard for me to simulate a case where for example the ReadStringAsync method returns a specific string I'm looking for...

**Comment by vtortola** [comment]
Just think about `WebSocketListener` like you would do about `TcpListener`. The right way of using it, is to have a wrapper class that implements one of your interfaces. That interface can be mocked and they you can test what happens when you receive a specific string. If in the future, you want to move to `System.Net.WebSockets`, you would just create a new implementation of your custom interface, and replace the one that wraps `WebSocketListener`; then you would have no dependency on my interfaces.

Cheers.

**Comment by ramlongcat** [comment]
yeah that's what i've done, it's just more painful.
TcpListener inability to be mocked is an issue, not a feature though :)
I'll mark this issue as solved.
