### ISSUE TITLE
Any suggestions on WebSocketListenerOptions?

### ISSUE THREAD

**Issue by pboyer** [vtortola/WebSocketListener#42]
I have a project where there will only be a single WebSocket at any given time, but a given WebSocket may require transporting a large amount in a given message (as much as a 32 mb).

Right now, my `WebSocketListenerOptions` look something like this:

```csharp
server = new WebSocketListener(endpoint, new WebSocketListenerOptions()
{
  PingTimeout = Timeout.InfiniteTimeSpan,
  SendBufferSize = 32768,
  WebSocketReceiveTimeout = TimeSpan.FromSeconds(15),
  WebSocketSendTimeout = TimeSpan.FromSeconds(15),
  BufferManager = BufferManager.CreateBufferManager((65536) * 1, 65536)
});
```

Does anything look incorrect here? Any suggestions would be very helpful.

**Comment by vtortola** [comment]
If you are going to have only one client connected, it may not be worth to use a buffer manager :) And if you still want to use it, use at least `* 5`  just in case since your client can disconnect and reconnect before the byte[] is returned to the buffer manager.

The send buffer value is something you probably want to experiment and check different approaches. Basically, the component will try to fill that buffer before sending, and then send a complete frame with that size. If it is to small, there are some little size over head because it implies more frame headers. If it is too big, control frames cannot be send in the middle of a data frame, only between frame and frame, so in a slow connection it may cause a timeout if the timeout value is low. There is a ping strategy for bandwidth saving where normal data also prevents the timeout from happening, but it is not in Nuget yet (it is in GitHub though, so you can try if you want).

Probably you want sorter timeouts, like 2 to 5 seconds, but again it depends.

**Comment by pboyer** [comment]
Thanks, I'll keep these in mind. :) 

I'm having a lot of fun with your project. AFAIK, you have the only open source WebSocket library for .NET that properly supports compression. Congrats.

**Comment by vtortola** [comment]
Thanks! :) However compression is a little bit crappy, because it only compress individual messages, but cannot take advantage of sharing the compression context across messages, which would yield a better compression. This limitation exists because how `DeflateStream` is simplemented.

However it would be still good for you since you plan to send big payloads :+1:
