### ISSUE TITLE
Subprotocol definition

### ISSUE THREAD

**Issue by jacobs100500** [vtortola/WebSocketListener#84]
Is it possible to disable the protocol definition? I don't specify the subprotocols on my server. Some clients may send their own protocol, and because it can't connect.
Error for example:
Client is requiring a sub protocol 'undefined' but there are not subprotocols defined.

**Comment by vtortola** [comment]
That seems like the client javascript error passing a variable that does not exists as subprotocol, isn't it? As far as I remember in the RFC, if a subprotocol is required by the client, the server must fulfill it or fail. I will check the RFC later.

**Comment by jacobs100500** [comment]
Yes, it's a browser error or the user manually specify the sub protocol. I don't specify the sub protocol in my javascript code. My server is not tied to any sub protocol, and therefore it does not matter which sub protocol is specified by the client.

**Comment by vtortola** [comment]
Actually after re-reading the RFC the server should not fail if the subprotocol required is not supported, it just should not return the `Sec-WebSocket-Protocol` header at all. I will fix this in the next day or two.

Thanks!

**Comment by vtortola** [comment]
Fixed in : https://github.com/vtortola/WebSocketListener/commit/0804d67fff18ff99fcd852be5f6860031d5ec269

However, it seems that the client can refuse to accept the fact that the server is not agreeing to any protocol. For example, in Google Chrome if you indicate a subprotocol but the server does not agree to it, it will fail with :  

> WebSocket connection to 'ws://localhost:8005/' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

So if you want to prevent the error, just add the subprotocol in the options like:

```
var server = new WebSocketListener(endpoint, new WebSocketListenerOptions()
{
    SubProtocols = new []{"text"},
});
```

Cheers.
