### ISSUE TITLE
Asserion Failed

### ISSUE THREAD

**Issue by tatulea** [vtortola/WebSocketListener#94]
Hi,

My application runs 24h on a Windows machine. Today, I found the error that you can see in the photo.
![eroare](https://cloud.githubusercontent.com/assets/11436915/21350722/b8e0541c-c6b0-11e6-83b7-242efb3d7456.png)

What could be the problem?

**Comment by vtortola** [comment]
I will fix this. Thanks!

**Comment by tatulea** [comment]
Thanks! Let me know when it's done. What is it about? :)

**Comment by vtortola** [comment]
I think the problem is that you have compiled it in DEBUG mode. Try to compile it in RELEASE and you should not see messages like that. This error just means that it was unable of write into the socket because maybe it is disconnected or something. Those dialog appear because it is calling `Debug.Fail` in order to help me to find issues when developing it, but when compiled in RELEASE mode, it does not show a dialog.
