### ISSUE TITLE
Port sharing with WebSocketListner, listening on a  server-ip/path/

### ISSUE THREAD

**Issue by omershib** [vtortola/WebSocketListener#97]
Hi

I have a question.

We currently use System.Net.Websockets and wish to try WebSocketListener.

We have a server application which spawns many server processes, each of these processes listens for  websocket connections on port 80 (or 443), and constitutes several websocket connections with the client.

To enable this simultaneous listening, we attach a unique GUID to each process, which then listens on "http://+:80/my-special-guid/" (simultaneously and uniquely).

Problem is I only see WebSocketListener constructors with IPEndpoint, and no path/suffix.
(In System.Net.Websockets, we use HttpListener's "Prefixes" attribute to add the suffix on which to listen.)
Is there a way to do this?

Thanks very much in advance.
Omer Shibolet.

**Comment by vtortola** [comment]
Hi,

A WebSocket is a socket service in itself, like HTTP or SMTP, so it is bound to a TCP port, and the port cannot be shared across processes unfortunately.

Now, IIS is able of sharing the same port for HTTP and WS or HTTPS and WSS, because it is implemented that way in the http.sys shipped with IIS 8 and further. It is a cool feature, but unfortunately is not something we the mortals can hook into as far as I know. And it is a pity because Microsoft's WebSocket API really sucks. As a side project I am creating a small utility named "WebSocketMvcController", which eases working with System.Net.Websockets in ASP.NET MVC (ie: is a controller you inherit from and gives you some methods to work with streams rather than that ugly API), and still I find it hard to use.

Regarding the path, in the same way than HTTP is bound to TCP 80 and you parse the path in the service itself, in WebSocketListener you are bound to a port and any parsing about paths or any logic beyond TCP needs to be done by yourself using the `Request` property.

The idea with this project, was to provide a bare-bones and asynchronous WebSocket server component with a more comprehensible API, and that worked in Windows 7. Serving HTTP or doing any kind or routing is beyond its scope, but do not let that stop you from fork it and adding it yourself.

**Comment by deniszykov** [comment]
Any plans to implement HTTP in WebSocketListener (or add interface to extend)? So we could serve HTTP and WS on same port.

**Comment by omershib** [comment]
Indeed, us mortals :)))

Thank you for this enlightening answer it was so helpful.

Apart from its akward API, our motivation for moving from system.net.websockets is the need for deflate extensions, which I couldn't find in system.net.websockets. Do you have an idea how use extensions with system.net.websockets?

Thanks again, Omer.

**Comment by vtortola** [comment]
@omershib it is not possible because you should set to 1 one of the bits in the frame to enable compression, but the `System.Net.WebSockets` API does not give you that control. It may be possible to alter the response headers during the handshake to indicate to the client that you accept the compression, still frames would be sent without it.

@deniszykov is not bad idea. It could fallback to another contract if the request is not a WebSocket. That contract would take control over the `NetworkStream` from that moment. And by default that interface would just throw an exception. I will give it a look this weekend.

**Comment by StefH** [comment]
If possible create a new branch for this functionaly. Or merge the .net core pr first.

**Comment by omershib** [comment]
Thanks, again Val, too bad :(

In your original reply, I didn't understand the IIS part. We use system.net.websockets and do port-sharing, without IIS, but in self-hosted processes. 
As far as I understand, Windows 8.1 and after include an updated http.sys which supports websockets. So non-IIS processes can too use this, by simply registering on port 80, using HttpListener?

I understand that in order to support Win7, TcpListener has to be used, but if I give this support up, wouldn't it be possible to combine HttpListener with your great API and extensibility, and allow for port 80 sharing?

Again, thanks so much.
Omer.

**Comment by deniszykov** [comment]
@vtortola it would be great! This would be an excellent replacement for little buggy HttpListener in Mono.

@omershib 
`The HTTP listener is part of the networking subsystem of Windows operating systems, and it is implemented as a kernel-mode device driver called the HTTP protocol stack (HTTP.sys). HTTP.sys listens for HTTP requests from the network, passes the requests onto IIS for processing, and then returns processed responses to client browsers. ` HttpListener use p/invoke to access **http.sys** API, so actually [Socket](https://msdn.microsoft.com/en-Us/library/system.net.sockets.socket(v=vs.110).aspx) is bound by http.sys and accessed via cross-process communcation by HttpListener. All dirty work (including  routing\filtering\parsing... ) is done by **http.sys**. In contrast, the WebSocketListener binds Socket in your process and do all work inside your process. So you can't share port(and Socket) between WebSocketListener and HttpListener because they are in different processes.

**Comment by vtortola** [comment]
@StefH  still did not had a chance to give a look to .NET core, and it does not seem it is gonna happen soon, but I am willing to merge if you tell me you will be more or less available to deal with issues I cannot. I would need though some changes in the folder structure, but I can do that myself.

@deniszykov  and @omershib to be honest I am not fan of serving files through a websocket component but since several people asked already, I think I can at least put a hook and make it totally optional.

**Comment by StefH** [comment]
@vtortola I'm available for questions and I can help you.

However, if you want to restructure the folders, I can also do that.

Like:
* rename "vtortola.Core.xxx" to "vtortola.xxx"
* move all source files from the root projects (e.g. vtortola.WebSockets) to that \src\... project structure.

About that *serving files through a websocket component*, maybe an idea to put this is in a new vtortola.WebSockets.Extensions / vtortola.WebSockets.FileServer project ?

**Comment by vtortola** [comment]
@StefH yes, but I need to put the hook in the main project, and then the optional implementation of that hook in the other assembly.
